Create database baseDados


CREATE TABLE TabEmpresa (
	idEmpresa INT AUTO_INCREMENT PRIMARY KEY,
	Nom VARCHAR(200) NOT NULL,
	TipoPessoa INT NOT NULL,
	Doc INT NOT NULL,
	Rgle VARCHAR(15),
	Nascimento DATE,
	Cep VARCHAR(8) NOT NULL,
	Logradouro VARCHAR(200) NOT NULL,
	Num INT NOT NULL , 
	Compl VARCHAR(50),
	Bairro VARCHAR(100) NOT NULL,
	Cidade VARCHAR(50) NOT NULL,
	Codlbge INT NOT NULL,
	Estado CHAR(2) NOT NULL,
	Sexo INT,
	Celular INT NOT NULL, 
	Email VARCHAR(100) NOT NULL,
	UsuarioPrincipal VARCHAR(20) NOT NULL,
	SenhaPrincipal VARCHAR(20) NOT NULL,
	Obs MEDIUMTEXT
)

CREATE TABLE TabCliente(
	idCliente INT AUTO_INCREMENT PRIMARY KEY,
    idEmpresa INT ,
	Nom VARCHAR (200) NOT NULL,
	TipoPesoa INT NOT NULL,
	Doc INT NOT NULL,
	Rgle VARCHAR(15) NOT NULL,
	Nascimento DATE,
	Sexo INT,
	Celular INT NOT NULL,
	Obs MEDIUMTEXT ,
	Log VARCHAR(60)
)

CREATE TABLE TabEnderecoCliente(
	idEmpresa INT NOT NULL,
	idCliente INT NOT NULL,
	idEndereco INT AUTO_INCREMENT PRIMARY KEY,
	Tipo INT NOT NULL,
	Cep INT NOt NULL,
	Logradouro VARCHAR(100),
	Num INT NOT NULL,
	Compl VARCHAR(100),
	Bairro VARCHAR(100) NOT NULL,
	Cidade VARCHAR(50) NOT NULL,
	CodIbge INT NOT NULL,
	Estado CHAR(2) NOT NULL ,
	PontoReferencia VARCHAR(200),
	Log VARCHAR(60) 
)

CREATE TABLE TabCaixa(
	idEmpresa INT NOT NULL,
	idCaixa  INT AUTO_INCREMENT PRIMARY KEY,
	NomCaixa INT NOT NULL,
	Dat DATE,
	Usuario VARCHAR(20) NOT NULL,
	Log VARCHAR(50)
)

CREATE TABLE TabCompra(
	idEmpresa INT NOT NULL, 
	idCompra INT NOT NULL,
	Fornecedor INT NOT NULL,
	Dat DATE NOT NULL,
	DatPrevEntrega DATE NOT NULL,
	DAtEntrega DATE, 
	Concluida CHAR(3),
	Obs MEDIUMTEXT, 
	Log VARCHAR (50) NOT NULL
)

CREATE TABLE TabPagtoCompra(
	idEmpresa INT NOT NULL,
	idCompra  INT NOT NULL,
	idItem  INT AUTO_INCREMENT PRIMARY KEY,
	Dat DATE NOT NULL,
	Forma INT NOT NULL, 
	Val FLOAT NOT NULL,
	Vencimento DATE NOT NULL,
	DatPagto DATE NOT NULL,
	Caixa INT NOT NULL,
	LancadoCaixa CHAR (3) NOT NULL,
	Log VARCHAR(50) NOT NULL
)

CREATE TABLE TabItemCompra(
	IdEmpresa INT NOT NULL,
	IdCompra INT NOT NULL,
	IdItem  INT AUTO_INCREMENT PRIMARY KEY,
	Quant INT,
	Produto INT NOT NULL,
	CodFabrica INT NOT NULL,
	Log VARCHAR(50) 
)

CREATE TABLE TabItemCaixa(
	IdEmpresa INT NOT NULL,
	IdCaixa INT NOT NULL,
	IdItem INT AUTO_INCREMENT PRIMARY KEY,
	Tipo INT NOT NULL,
	Conta  INT NOT NULL,
	Historico VARCHAR(250) NOT NULL,
	Val FLOAT NOT NULL,
	Forma INT NOT NULL,
	Log VARCHAR(50) NOT NULL
)

CREATE TABLE TabFornecedor(
	IdEmpresa INT NOT NULL,
	IdFornecedor INT AUTO_INCREMENT PRIMARY KEY,
	Nom VARCHAR(200) NOT NULL,
	TipoPessoa INT NOT NULL,
	Doc INT NOT NULL,
	Rgle  VARCHAR(50) NOT NULL,
	Celular INT NOT NULL,
	Email  VARCHAR(100) NOT NULL,
	Obs VARCHAR(100),
	Log VARCHAR(50) NOT NULL,
	Cep VARCHAR(8) NOT NULL,
	Logradouro VARCHAR(20) NOT NULL,
	Num INT NOT NULL,
	Compl  VARCHAR(50) NOT NULL,
	Bairro  VARCHAR(50) NOT NULL,
	Cidade VARCHAR(50) NOT NULL,
	Estado CHAR(2) NOT NULL,
	PontoReferencia VARCHAR(100) NOT NULL
)

CREATE TABLE TabProduto(
	IdEmpresa INT NOT NULL,
	IdProduto INT AUTO_INCREMENT PRIMARY KEY,
	Descricao VARCHAR(200) NOT NULL,
	Unidade CHAR(2) NOT NULL,
	Preco FLOAT NOT NULL,
	CodFabrica INT NOT NULL,
	Obs VARCHAR(100),
	Log VARCHAR(50) NOT NULL
)

CREATE TABLE TabVenda(
	idEmpresa INT NOT NULL,
	IdVenda  INT AUTO_INCREMENT PRIMARY KEY,
	Dat DATE, 
	Cliente INT NOT NULL,
	EnderecoSelecionado INT NOT NULL,
	Obs MEDIUMTEXT,
	Concluida CHAR(3),
	Log VARCHAR(50) NOT NULL
)

CREATE TABLE TabItemVenda(
	IdEmpresa INT NOT NULL,
	IdVenda INT NOT NULL,
	IdItem INT AUTO_INCREMENT PRIMARY KEY,
	Quant INT NOT NULL,
	Produto INT NOT NULL,
	Log VARCHAR(50) NOT NULL
)

CREATE TABLE TabPagtoVenda(
	IdEmpresa INT NOT NULL,
	IdVenda INT NOT NULL,
	IdItem INT AUTO_INCREMENT PRIMARY KEY,
	Dat DATE,
	Forma INT NOT NULL,
	Val FLOAT NOT NULL,
	Vencimento DATE NOT NULL,
	DatPagto DATE NOT NULL,
	Caixa INT NOT NULL,
	LancadoCaixa CHAR(3) NOT NULL,
	Log VARCHAR(50) NOT NULL
)

CREATE TABLE TabPlanoConta(
	IdConta INT AUTO_INCREMENT PRIMARY KEY,
	Ordem VARCHAR(20),
	Tipo1 VARCHAR(30),
	Tipo2 VARCHAR(30),
	TIpo3 VARCHAR(30)
)

CREATE TABLE TabNomCaixa(
	IdEmpresa INT NOT NULL,
	IdNomCaixa INT AUTO_INCREMENT PRIMARY KEY,
	Nom VARCHAR(100),
	Log VARCHAR(50)
)
